<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>Vocabularity-local-development</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.3.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <ProjectReference Include="../Vocabularity.Infrastructure/Vocabularity.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" PrivateAssets="all" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="7.3.1" />
  </ItemGroup>
</Project>
